--candidatos a magistrado

INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'BARRETO ARDILA BLANCA NELIDA', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'CASTAÑEDA CRESPO CARLOS EDUARDO', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'DÍAZ SOTO JORGE HERNÁN', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ESCOBAR GIL ÁLVARO RICARDO', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'HERNÁNDEZ MINDIOLA MARÍA LOURDES', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'JALLER SERPA RONALD AMETH', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'OVIEDO PINTO MARÍA LEONOR', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'RAMÍREZ MONTES SANDRA PATRICIA', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'SANJUAN GÁLVEZ JORGE ENRIQUE', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'TORRES RODRÍGUEZ FLOR ALBA', 'Aspirante Sala Especial de 1ra Instancia', current_timestamp, current_timestamp, NULL, 1);

INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ALARCÓN PALACIO YADIRA ELENA', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ESTRADA SANÍN DARÍO IGNACIO', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'FERNÁNDEZ MUÑOZ MÓNICA LUCÍA', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'GIACOMETTE FERRER ANA ZENOBIA', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'GONZÁLEZ NEIRA HILDA', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ISAZA DÁVILA JOSÉ ALFONSO', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'JIMÉNEZ VALDERRAMA FERNANDO AUGUSTO', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'LEÓN ROBAYO EDGAR IVÁN', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MONTEALEGRE VARÓN MABEL', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'QUINTERO GARCÍA ORLANDO', 'Aspirante Sala de Casación Civil', current_timestamp, current_timestamp, NULL, 1);

INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'CASTRO DÍAZ JAVIER FERNANDO', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'COLORADO ACEVEDO DIANA DEL PILAR', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'CUEVAS VALBUENA LUIS ENRIQUE', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ESCRUCERÍA MAYOLO IVÁN HUMBERTO', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MERCHÁN CALDERÓN OLGA YINETH', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MORENO VARGAS RAFAEL', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'NIÑO VÁSQUEZ DIEGO FERNANDO', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'OSPINA GAITÁN MARTHA RUTH', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'SANDOVAL ISDITH LUIS EDUARDO', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'URRESTA TASCÓN MÓNICA MARÍA', 'Aspirante Sala de Descongestión Laboral', current_timestamp, current_timestamp, NULL, 1);

--candidatos terna procurador
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ACOSTA MAESTRE ROBERTO CARLOS ', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ARELLANO JARAMILLO LUIS EDUARDO ', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'BERNAL MONTENEGRO GERARDO ', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'BOLAÑOS JIMÉNEZ JUAN CARLOS ', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'BUITRAGO GÓMEZ WILFORD HOLMEDO ', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'CASTAÑEDA HERNÁNDEZ LUIS ALBERTO', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'CASTAÑEDA VILLAMIZAR CARMEN TERESA', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'GIL BOTERO ENRIQUE DE JESÚS', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'GONZÁLEZ VILLA JULIO ENRIQUE', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MÁRQUEZ RODRÍGUEZ MARCELA', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MARTÍNEZ QUINTERO RICARDO', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MOLINA ARRUBLA CARLOS MARIO', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'OSORIO RUÍZ JOSÉ JOAQUÍN', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'OTÁLORA GÓMEZ JORGE ARMANDO', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'PÁEZ SAAVEDRA LEONARDO', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'PAREDES CIFUENTES CARLOS RAFAEL', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'PINEDA VILLAMIZAR RITA ELVIRA', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'RESTREPO GARCÍA JOSÉ FREDDY', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'RUÍZ OREJUELA WILSON', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'YEPES BARREIRO ALBERTO', 'Aspirante a Procurador', current_timestamp, current_timestamp, NULL, 1);
