

INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'BARRETO ARDILA BLANCA NELIDA', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'CASTAÑEDA CRESPO CARLOS EDUARDO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'DÍAZ SOTO JORGE HERNÁN', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ESCOBAR GIL ÁLVARO RICARDO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'HERNÁNDEZ MINDIOLA MARÍA LOURDES', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'JALLER SERPA RONALD AMETH', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'OVIEDO PINTO MARÍA LEONOR', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'RAMÍREZ MONTES SANDRA PATRICIA', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'SANJUAN GÁLVEZ JORGE ENRIQUE', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'TORRES RODRÍGUEZ FLOR ALBA', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ALARCÓN PALACIO YADIRA ELENA', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ESTRADA SANÍN DARÍO IGNACIO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'FERNÁNDEZ MUÑOZ MÓNICA LUCÍA', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'GIACOMETTE FERRER ANA ZENOBIA', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'GONZÁLEZ NEIRA HILDA', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ISAZA DÁVILA JOSÉ ALFONSO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'JIMÉNEZ VALDERRAMA FERNANDO AUGUSTO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'LEÓN ROBAYO EDGAR IVÁN', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MONTEALEGRE VARÓN MABEL', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'QUINTERO GARCÍA ORLANDO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'CASTRO DÍAZ JAVIER FERNANDO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'COLORADO ACEVEDO DIANA DEL PILAR', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'CUEVAS VALBUENA LUIS ENRIQUE', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'ESCRUCERÍA MAYOLO IVÁN HUMBERTO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MERCHÁN CALDERÓN OLGA YINETH', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'MORENO VARGAS RAFAEL', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'NIÑO VÁSQUEZ DIEGO FERNANDO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'OSPINA GAITÁN MARTHA RUTH', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'SANDOVAL ISDITH LUIS EDUARDO', '', current_timestamp, current_timestamp, NULL, 1);
INSERT INTO candidato (id, "Nombre", "Descripcion", "fechaCreacion", "fechaEdicion", "fechaEliminacion", "EstadoRegistro") VALUES(uuid_generate_v4(), 'URRESTA TASCÓN MÓNICA MARÍA', '', current_timestamp, current_timestamp, NULL, 1);

