
version: '3.5'

services:

  demokratianweb-prod:
    container_name: demokratian-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8084:80'
    volumes:      
      - uploadVolume:/var/Uploads
volumes:
  uploadVolume: {}

#docker-compose -f docker-compose.yml up --build -d



#push image
#docker tag 2fc103d29800 senseiroa/votaciones-prod:v2
#docker push senseiroa/votaciones-prod:v2
#

#ejecutar
#docker run -d -p 8085:80 --name demokratianwebv2 senseiroa/votaciones-prod:v2
#
#
